// Generated by CoffeeScript 1.12.3
(function() {
  var Cylon, SerialPort, port, ports, randomColor, randomNumber, shake, startTimer, stop, timer;

  Cylon = require('cylon');

  SerialPort = require('serialport');

  ports = ['/dev/rfcomm0'];

  port = new SerialPort(ports[0]);

  randomNumber = function(max) {
    if (max < 0) {
      return 0;
    } else {
      return max * Math.random();
    }
  };

  randomColor = function() {
    var b, g, r, total;
    total = 255;
    r = randomNumber(total);
    g = randomNumber(total - r);
    b = randomNumber(total - r - g);
    return r << 16 | g << 8 | b;
  };

  stop = function(my) {
    my.sphero.setRawMotors({
      lmode: 0,
      rmode: 0
    });
    return my.sphero.setStabilization(true);
  };

  shake = function(my) {
    my.sphero.setStabilization(false);
    my.sphero.setRawMotors({
      lmode: 1,
      lpower: 250,
      rmode: 1,
      rpower: 250
    });
    return setTimeout((function() {
      return stop(my);
    }), 3000);
  };

  timer = null;

  startTimer = function(my) {
    clearTimeout(timer);
    return timer = setTimeout((function() {
      return shake(my);
    }), 6000);
  };

  Cylon.robot({
    connections: {
      sphero: {
        adaptor: 'sphero',
        port: ports[0]
      }
    },
    devices: {
      sphero: {
        driver: 'sphero'
      }
    },
    work: function(my) {
      var color;
      color = 0;
      my.sphero.on('collision', function(data) {
        color = randomColor();
        my.sphero.color(color);
        return startTimer(my);
      });
      my.sphero.detectCollisions();
      my.sphero.setStabilization(true);
      return startTimer(my);
    }
  });

  port.on('open', function() {
    console.log('connection opened');
    return setTimeout((function() {
      return Cylon.start();
    }), 3000);
  });

}).call(this);
