// Generated by CoffeeScript 1.12.3
(function() {
  var Cylon, SerialPort, color, countdown, nextBlink, port, ports, randomColor, randomNumber, shake, stop, timer;

  Cylon = require('cylon');

  SerialPort = require('serialport');

  timer = null;

  countdown = 0;

  color = 0;

  ports = ['/dev/rfcomm0'];

  port = new SerialPort(ports[0]);

  randomNumber = function(max) {
    if (max < 0) {
      return 0;
    } else {
      return max * Math.random();
    }
  };

  randomColor = function() {
    var b, g, r, total;
    total = 255;
    r = randomNumber(total);
    g = randomNumber(total - r);
    b = randomNumber(total - r - g);
    return r << 16 | g << 8 | b;
  };

  stop = function(my) {
    my.sphero.setRawMotors({
      lmode: 0,
      rmode: 0
    });
    my.sphero.setStabilization(true);
    color = randomColor();
    countdown = 1000;
    return nextBlink(my, 1);
  };

  shake = function(my) {
    my.sphero.setStabilization(false);
    my.sphero.setRawMotors({
      lmode: 1,
      lpower: 250,
      rmode: 1,
      rpower: 250
    });
    return setTimeout((function() {
      return stop(my);
    }), 3000);
  };

  nextBlink = function(my, lit) {
    clearTimeout(timer);
    countdown *= 0.9;
    my.sphero.color(lit * color);
    if (countdown > 10) {
      return timer = setTimeout((function() {
        return nextBlink(my, lit === 1 ? 0 : 1);
      }), countdown);
    } else {
      return shake(my);
    }
  };

  Cylon.robot({
    connections: {
      sphero: {
        adaptor: 'sphero',
        port: ports[0]
      }
    },
    devices: {
      sphero: {
        driver: 'sphero'
      }
    },
    work: function(my) {
      my.sphero.on('collision', function(data) {
        color = randomColor();
        countdown = 1000;
        return nextBlink(my, 1);
      });
      my.sphero.detectCollisions();
      my.sphero.setStabilization(true);
      return nextBlink(my, 1);
    }
  });

  port.on('open', function() {
    console.log('connection opened');
    return setTimeout((function() {
      return Cylon.start();
    }), 3000);
  });

}).call(this);
